// SPDX-FileCopyrightText: 2026 Blufio Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Systemd timer and service unit file generation.

use blufio_core::BlufioError;
use std::path::{Path, PathBuf};

/// A cron job row from the `cron_jobs` table, used for timer generation.
#[derive(Debug, Clone)]
pub struct CronJobRow {
    pub name: String,
    pub schedule: String,
    pub task: String,
    pub enabled: bool,
}

const TIMER_TEMPLATE: &str = "# Generated by blufio cron generate-timers\n# Do not edit manually -- regenerate with: blufio cron generate-timers\n[Unit]\nDescription=Blufio cron: {job_name}\n\n[Timer]\nOnCalendar={on_calendar}\nAccuracySec=1min\nPersistent=true\n\n[Install]\nWantedBy=timers.target\n";

const SERVICE_TEMPLATE: &str = "# Generated by blufio cron generate-timers\n[Unit]\nDescription=Blufio cron job: {job_name}\n\n[Service]\nType=oneshot\nExecStart={blufio_path} cron run-now {job_name}\n";

/// Generate systemd timer and service unit files for all enabled cron jobs.
pub fn generate_timers(
    jobs: &[CronJobRow],
    blufio_path: &str,
    output_dir: &Path,
) -> Result<Vec<PathBuf>, BlufioError> {
    let mut created_files = Vec::new();

    for job in jobs {
        if !job.enabled {
            continue;
        }

        let on_calendar = match cron_to_on_calendar(&job.schedule) {
            Ok(cal) => cal,
            Err(warning) => {
                eprintln!(
                    "warning: job '{}': could not convert '{}': {}. Using hourly fallback.",
                    job.name, job.schedule, warning
                );
                "*-*-* *:00:00".to_string()
            }
        };

        let safe_name = job
            .name
            .replace(|c: char| !c.is_alphanumeric() && c != '-' && c != '_', "-");

        let timer_content = TIMER_TEMPLATE
            .replace("{job_name}", &job.name)
            .replace("{on_calendar}", &on_calendar);
        let timer_path = output_dir.join(format!("blufio-cron-{safe_name}.timer"));
        std::fs::write(&timer_path, &timer_content).map_err(|e| {
            BlufioError::Internal(format!("Failed to write {}: {e}", timer_path.display()))
        })?;
        created_files.push(timer_path);

        let service_content = SERVICE_TEMPLATE
            .replace("{job_name}", &job.name)
            .replace("{blufio_path}", blufio_path);
        let service_path = output_dir.join(format!("blufio-cron-{safe_name}.service"));
        std::fs::write(&service_path, &service_content).map_err(|e| {
            BlufioError::Internal(format!("Failed to write {}: {e}", service_path.display()))
        })?;
        created_files.push(service_path);
    }

    Ok(created_files)
}

fn cron_to_on_calendar(schedule: &str) -> Result<String, String> {
    let fields: Vec<&str> = schedule.split_whitespace().collect();
    if fields.len() != 5 {
        return Err(format!("expected 5 fields, got {}", fields.len()));
    }
    for field in &fields {
        if field.contains('L') || field.contains('W') || field.contains('#') {
            return Err("L/W/# specifiers not supported".to_string());
        }
    }
    let dow_part = convert_dow(fields[4])?;
    let month_part = convert_field(fields[3])?;
    let dom_part = convert_field(fields[2])?;
    let hour_part = convert_time_field(fields[1])?;
    let minute_part = convert_time_field(fields[0])?;
    let date_part = format!("*-{month_part}-{dom_part}");
    let time_part = format!("{hour_part}:{minute_part}:00");
    if let Some(dow_str) = dow_part {
        Ok(format!("{dow_str} {date_part} {time_part}"))
    } else {
        Ok(format!("{date_part} {time_part}"))
    }
}

fn convert_dow(dow: &str) -> Result<Option<String>, String> {
    if dow == "*" {
        return Ok(None);
    }
    let dow_names = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
    let mut names = Vec::new();
    for part in dow.split(',') {
        if let Ok(n) = part.parse::<u8>() {
            if n > 6 {
                return Err(format!("invalid dow: {n}"));
            }
            names.push(dow_names[n as usize].to_string());
        } else if part.contains('-') {
            let rp: Vec<&str> = part.split('-').collect();
            if rp.len() != 2 {
                return Err(format!("invalid dow range: {part}"));
            }
            let s: u8 = rp[0]
                .parse()
                .map_err(|_| format!("invalid dow: {}", rp[0]))?;
            let e: u8 = rp[1]
                .parse()
                .map_err(|_| format!("invalid dow: {}", rp[1]))?;
            if s > 6 || e > 6 {
                return Err(format!("invalid dow range: {part}"));
            }
            for i in s..=e {
                names.push(dow_names[i as usize].to_string());
            }
        } else {
            return Err(format!("unsupported dow: {part}"));
        }
    }
    Ok(Some(names.join(",")))
}

fn convert_field(field: &str) -> Result<String, String> {
    if field == "*" {
        return Ok("*".to_string());
    }
    if let Some(step) = field.strip_prefix("*/") {
        let _: u32 = step.parse().map_err(|_| format!("invalid step: {step}"))?;
        return Err(format!("step '{field}' in date fields not supported"));
    }
    let parts: Vec<String> = field
        .split(',')
        .map(|p| {
            if let Ok(n) = p.parse::<u32>() {
                Ok(format!("{n:02}"))
            } else if p.contains('-') {
                Ok(p.to_string())
            } else {
                Err(format!("unsupported value: {p}"))
            }
        })
        .collect::<Result<Vec<_>, _>>()?;
    Ok(parts.join(","))
}

fn convert_time_field(field: &str) -> Result<String, String> {
    if field == "*" {
        return Ok("*".to_string());
    }
    if let Some(step) = field.strip_prefix("*/") {
        let n: u32 = step.parse().map_err(|_| format!("invalid step: {step}"))?;
        return Ok(format!("00/{n}"));
    }
    if field.contains('/') {
        let parts: Vec<&str> = field.split('/').collect();
        if parts.len() == 2 {
            return Ok(format!("{}/{}", parts[0], parts[1]));
        }
    }
    let parts: Vec<String> = field
        .split(',')
        .map(|p| {
            if let Ok(n) = p.parse::<u32>() {
                Ok(format!("{n:02}"))
            } else if p.contains('-') {
                Ok(p.to_string())
            } else {
                Err(format!("unsupported value: {p}"))
            }
        })
        .collect::<Result<Vec<_>, _>>()?;
    Ok(parts.join(","))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_cron_to_on_calendar_daily() {
        assert_eq!(cron_to_on_calendar("0 2 * * *").unwrap(), "*-*-* 02:00:00");
    }

    #[test]
    fn test_cron_to_on_calendar_every_15_min() {
        assert_eq!(
            cron_to_on_calendar("*/15 * * * *").unwrap(),
            "*-*-* *:00/15:00"
        );
    }

    #[test]
    fn test_cron_to_on_calendar_every_6_hours() {
        assert_eq!(
            cron_to_on_calendar("0 */6 * * *").unwrap(),
            "*-*-* 00/6:00:00"
        );
    }

    #[test]
    fn test_cron_to_on_calendar_weekly_sunday() {
        assert_eq!(
            cron_to_on_calendar("0 0 * * 0").unwrap(),
            "Sun *-*-* 00:00:00"
        );
    }

    #[test]
    fn test_cron_to_on_calendar_monthly_first() {
        assert_eq!(cron_to_on_calendar("0 0 1 * *").unwrap(), "*-*-01 00:00:00");
    }

    #[test]
    fn test_cron_to_on_calendar_complex_rejects() {
        assert!(cron_to_on_calendar("0 0 L * *").is_err());
        assert!(cron_to_on_calendar("0 0 15W * *").is_err());
    }

    #[test]
    fn test_generate_timers() {
        let dir = TempDir::new().unwrap();
        let jobs = vec![
            CronJobRow {
                name: "backup".into(),
                schedule: "0 2 * * *".into(),
                task: "backup".into(),
                enabled: true,
            },
            CronJobRow {
                name: "disabled".into(),
                schedule: "0 0 * * *".into(),
                task: "health_check".into(),
                enabled: false,
            },
        ];
        let paths = generate_timers(&jobs, "/usr/local/bin/blufio", dir.path()).unwrap();
        assert_eq!(paths.len(), 2);
        let timer = std::fs::read_to_string(&paths[0]).unwrap();
        assert!(timer.contains("OnCalendar=*-*-* 02:00:00"));
        let service = std::fs::read_to_string(&paths[1]).unwrap();
        assert!(service.contains("ExecStart=/usr/local/bin/blufio cron run-now backup"));
    }
}
