// SPDX-FileCopyrightText: 2026 Blufio Contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

//! `blufio litestream` subcommand implementation.
//!
//! Provides tooling for Litestream WAL replication integration:
//! - `blufio litestream init`: Generate a `litestream.yml` config template
//! - `blufio litestream status`: Check replication status via the litestream binary

use std::path::Path;

use blufio_config::model::BlufioConfig;
use blufio_core::BlufioError;
use tracing::{info, warn};

/// Check if the `litestream` binary is available in PATH.
fn litestream_binary_exists() -> bool {
    std::process::Command::new("which")
        .arg("litestream")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Determine if SQLCipher encryption is active.
///
/// Checks the `BLUFIO_DB_KEY` environment variable, which is the standard
/// mechanism for providing the SQLCipher encryption key at runtime.
fn is_encryption_active() -> bool {
    std::env::var("BLUFIO_DB_KEY").is_ok()
}

/// Derive the audit database path from the main database path.
///
/// Following Phase 54 convention: audit.db sits beside the main DB
/// in the same directory.
fn audit_db_path(db_path: &str) -> String {
    let p = Path::new(db_path);
    let parent = p.parent().unwrap_or(Path::new("."));
    parent.join("audit.db").to_string_lossy().to_string()
}

/// Derive the litestream.yml output path from the main database path.
fn litestream_config_path(db_path: &str) -> String {
    let p = Path::new(db_path);
    let parent = p.parent().unwrap_or(Path::new("."));
    parent.join("litestream.yml").to_string_lossy().to_string()
}

/// Generate the YAML template content for Litestream configuration.
pub fn generate_template(db_path: &str, audit_path: &str) -> String {
    format!(
        r#"# Litestream configuration for Blufio
# Generated by: blufio litestream init
#
# WARNING: Litestream is INCOMPATIBLE with SQLCipher encrypted databases.
# If encryption is enabled, use `blufio backup` + cron instead.
# See: https://github.com/benbjohnson/litestream/issues/177
#
# Documentation: https://litestream.io/reference/config/

dbs:
  - path: {db_path}
    replicas:
      - type: s3
        bucket: your-bucket-name
        path: blufio/main
        region: us-east-1
        access-key-id: YOUR_ACCESS_KEY
        secret-access-key: YOUR_SECRET_KEY
        retention: 72h
        snapshot-interval: 24h

  - path: {audit_path}
    replicas:
      - type: s3
        bucket: your-bucket-name
        path: blufio/audit
        region: us-east-1
        access-key-id: YOUR_ACCESS_KEY
        secret-access-key: YOUR_SECRET_KEY
        retention: 168h
        snapshot-interval: 24h
"#,
        db_path = db_path,
        audit_path = audit_path,
    )
}

/// Run `blufio litestream init`.
///
/// Generates a `litestream.yml` configuration template alongside the database
/// file. Warns if the litestream binary is not installed and if SQLCipher
/// encryption is active (incompatible with Litestream).
pub fn run_litestream_init(config: &BlufioConfig) -> Result<(), BlufioError> {
    let db_path = &config.storage.database_path;
    let audit_path = audit_db_path(db_path);
    let config_path = litestream_config_path(db_path);

    // Check for litestream binary.
    if !litestream_binary_exists() {
        eprintln!(
            "WARNING: litestream binary not found in PATH.\n\
             Install Litestream: https://litestream.io/install/\n\
             The config template will still be generated.\n"
        );
        warn!("litestream binary not found in PATH");
    }

    // Check for SQLCipher incompatibility.
    if is_encryption_active() {
        eprintln!(
            "WARNING: SQLCipher encryption is active (BLUFIO_DB_KEY is set).\n\
             Litestream is INCOMPATIBLE with SQLCipher encrypted databases.\n\
             Recommended alternative: `blufio backup` + cron for scheduled backups.\n\
             See: https://github.com/benbjohnson/litestream/issues/177\n\
             \n\
             Generating template anyway for reference...\n"
        );
        warn!("Litestream config generated but SQLCipher encryption is active -- incompatible");
    }

    // Generate template.
    let template = generate_template(db_path, &audit_path);

    // Ensure parent directory exists.
    if let Some(parent) = Path::new(&config_path).parent()
        && !parent.as_os_str().is_empty()
        && !parent.exists()
    {
        std::fs::create_dir_all(parent).map_err(|e| {
            BlufioError::Config(format!(
                "failed to create directory {}: {}",
                parent.display(),
                e
            ))
        })?;
    }

    // Write the template file.
    std::fs::write(&config_path, &template).map_err(|e| {
        BlufioError::Config(format!(
            "failed to write litestream config to {}: {}",
            config_path, e
        ))
    })?;

    info!(path = %config_path, "litestream config template written");

    println!("Litestream config template written to: {config_path}");
    println!();
    println!("Next steps:");
    println!("  1. Edit {config_path} with your S3 bucket and credentials");
    println!("  2. Start replication:");
    println!("     litestream replicate -config {config_path}");
    println!();
    println!("  Databases configured:");
    println!("    - Main:  {db_path}");
    println!("    - Audit: {audit_path}");

    Ok(())
}

/// Parse a line from `litestream generations` output.
///
/// The output format varies by version, but typically includes generation name,
/// index, and offset information. We extract what we can.
fn parse_generations_output(stdout: &str) -> Vec<String> {
    stdout
        .lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| line.trim().to_string())
        .collect()
}

/// Run `blufio litestream status`.
///
/// Shells out to the litestream binary to check replication status.
/// Reports generation information for the configured databases.
pub fn run_litestream_status(config: &BlufioConfig) -> Result<(), BlufioError> {
    let db_path = &config.storage.database_path;
    let config_path = litestream_config_path(db_path);

    // Check for litestream binary.
    if !litestream_binary_exists() {
        eprintln!(
            "ERROR: litestream binary not found in PATH.\n\
             Install Litestream: https://litestream.io/install/"
        );
        return Err(BlufioError::Config(
            "litestream binary not found".to_string(),
        ));
    }

    // Check if litestream is enabled in config.
    if !config.litestream.enabled {
        eprintln!(
            "WARNING: Litestream is not enabled in configuration.\n\
             Set [litestream].enabled = true in blufio.toml to enable.\n"
        );
        warn!("litestream status check called but litestream not enabled in config");
    }

    // Check if config file exists.
    if !Path::new(&config_path).exists() {
        eprintln!(
            "Litestream config not found at: {config_path}\n\
             Run `blufio litestream init` to generate a config template."
        );
        return Err(BlufioError::Config(format!(
            "litestream config not found at {}",
            config_path
        )));
    }

    println!("Litestream replication status");
    println!("{}", "-".repeat(50));
    println!("Config: {config_path}");
    println!("DB:     {db_path}");
    println!();

    // Shell out to `litestream generations` to check status.
    match std::process::Command::new("litestream")
        .args(["generations", "-config", &config_path])
        .output()
    {
        Ok(output) => {
            if output.status.success() {
                let stdout = String::from_utf8_lossy(&output.stdout);
                let lines = parse_generations_output(&stdout);
                if lines.is_empty() {
                    println!("No generations found. Replication may not be running.");
                    println!("Start with: litestream replicate -config {config_path}");
                } else {
                    println!("Generations:");
                    for line in &lines {
                        println!("  {line}");
                    }
                }
            } else {
                let stderr = String::from_utf8_lossy(&output.stderr);
                eprintln!("litestream generations failed:");
                eprintln!("  {}", stderr.trim());
                eprintln!();
                eprintln!("Ensure replication is running:");
                eprintln!("  litestream replicate -config {config_path}");
            }
        }
        Err(e) => {
            eprintln!("Failed to execute litestream: {e}");
            return Err(BlufioError::Config(format!(
                "failed to execute litestream: {}",
                e
            )));
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_contains_both_db_paths() {
        let template = generate_template("/data/blufio.db", "/data/audit.db");
        assert!(template.contains("/data/blufio.db"));
        assert!(template.contains("/data/audit.db"));
    }

    #[test]
    fn template_contains_s3_stanza() {
        let template = generate_template("/data/blufio.db", "/data/audit.db");
        assert!(template.contains("type: s3"));
        assert!(template.contains("bucket: your-bucket-name"));
        assert!(template.contains("access-key-id:"));
        assert!(template.contains("secret-access-key:"));
    }

    #[test]
    fn template_contains_warning_comment() {
        let template = generate_template("/data/blufio.db", "/data/audit.db");
        assert!(template.contains("INCOMPATIBLE with SQLCipher"));
        assert!(template.contains("litestream.io/reference/config"));
    }

    #[test]
    fn template_has_retention_settings() {
        let template = generate_template("/data/blufio.db", "/data/audit.db");
        assert!(template.contains("retention: 72h"));
        assert!(template.contains("retention: 168h"));
        assert!(template.contains("snapshot-interval: 24h"));
    }

    #[test]
    fn template_has_separate_replica_paths() {
        let template = generate_template("/data/blufio.db", "/data/audit.db");
        assert!(template.contains("path: blufio/main"));
        assert!(template.contains("path: blufio/audit"));
    }

    #[test]
    fn audit_db_path_derives_correctly() {
        assert_eq!(audit_db_path("/data/blufio.db"), "/data/audit.db");
        assert_eq!(audit_db_path("blufio.db"), "audit.db");
    }

    #[test]
    fn litestream_config_path_derives_correctly() {
        assert_eq!(
            litestream_config_path("/data/blufio.db"),
            "/data/litestream.yml"
        );
        assert_eq!(litestream_config_path("blufio.db"), "litestream.yml");
    }

    #[test]
    fn parse_generations_filters_empty_lines() {
        let output = "gen1 info\n\ngen2 info\n  \n";
        let lines = parse_generations_output(output);
        assert_eq!(lines.len(), 2);
        assert_eq!(lines[0], "gen1 info");
        assert_eq!(lines[1], "gen2 info");
    }

    #[test]
    fn parse_generations_empty_output() {
        let lines = parse_generations_output("");
        assert!(lines.is_empty());
    }

    #[test]
    fn sqlcipher_warning_detects_env_var() {
        // Note: we test the helper function directly.
        // In CI, BLUFIO_DB_KEY is not set, so this should return false.
        // We verify the function is callable and returns a bool.
        let _result = is_encryption_active();
    }
}
